### ISSUE TITLE
Error when installing bow-openapi using homebrew on macOS Big Sur 

### ISSUE THREAD

**Issue by lyzkov** [bow-swift/bow-openapi#39]
```
==> Installing bow-openapi from bow-swift/bow
swagger-codegen: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.
```

Homebrew shows this error message even after `adoptopenjdk8` successful installation.

**Comment by miguelangel-dev** [comment]
Ey @lyzkov!

I understand you have tried to install AdoptOpenJDK from Homebrew (following the suggestions) and you have Xcode & CLT at 12.x. In this case, and as it is in beta, I suggest you to try to install `bow-openapi` manually.

Please, let me know if it works! :)

------------

### How to install Bow OpenAPI manually?

#### Prerequisites
You need to have installed `swagger-codegen` (bow-openapi is built on top of this tool) - [here](https://github.com/swagger-api/swagger-codegen#prerequisites)  you can find the steps to do it from homebrew (it seems to be what is failing you) or manually directly from Maven.org.

#### Install Bow OpenAPI
1. Download the [release 0.2](https://github.com/bow-swift/bow-openapi/archive/0.2.0.zip)
2. In the root folder run: `make macos`

**Comment by lyzkov** [comment]
Yes, it works. Thank you very much!

**Comment by miguelangel-dev** [comment]
Once Big Sur is released, we will come back to check everything is working correctly.
